# 📊 Math Evaluator Engine (ML Metrics from Scratch)
# File: D:\DA + DE\PYTHON_PROJECTS\06_diabetes_predictor\evaluator.py
import json
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def calculate_confusion_matrix(y_true, y_pred):
    """
    Calculates True Positives, True Negatives, False Positives, and False Negatives.
    """
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    
    # YOUR TASK 1: Loop through y_true and y_pred using zip()
    # and increment tp, tn, fp, and fn based on their values.
    # - True Positive: actual = 1, predicted = 1
    # - True Negative: actual = 0, predicted = 0
    # - False Positive: actual = 0, predicted = 1
    # - False Negative: actual = 1, predicted = 0
    
    for actual, predicted in zip(y_true, y_pred):
        if actual == 1 and predicted == 1:
            tp += 1
        elif actual == 0 and predicted == 0:
            tn += 1
        elif actual == 0 and predicted == 1:
            fp += 1
        elif actual == 1 and predicted == 0:
            fn += 1
    
    return tp, tn, fp, fn

def calculate_metrics(tp, tn, fp, fn):
    """
    Calculates Accuracy, Precision, Recall, and F1-Score from scratch.
    """
    # YOUR TASK 2: Implement the math formulas for:
    # - Accuracy: (TP + TN) / Total
    # - Precision: TP / (TP + FP)
    # - Recall: TP / (TP + FN)
    # - F1-Score: 2 * (Precision * Recall) / (Precision + Recall)
    # Hint: Check for division by zero!
    
    total = tp + tn + fp + fn
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    return accuracy, precision, recall, f1

if __name__ == "__main__":
    # Load test results generated by train.py
    try:
        with open("evaluation_data.json", "r") as f:
            data = json.load(f)
            y_test = data["y_test"]
            y_pred = data["y_pred"]
    except FileNotFoundError:
        print("[Error] evaluation_data.json not found. Run train.py first!")
        exit(1)
        
    # Calculate metrics from scratch
    tp, tn, fp, fn = calculate_confusion_matrix(y_test, y_pred)
    acc, prec, rec, f1 = calculate_metrics(tp, tn, fp, fn)
    
    print("=== MANUAL EVALUATOR (Math from Scratch) ===")
    print(f"True Positives:  {tp}")
    print(f"True Negatives:  {tn}")
    print(f"False Positives: {fp}")
    print(f"False Negatives: {fn}")
    print(f"Accuracy:        {acc:.4f}")
    print(f"Precision:       {prec:.4f}")
    print(f"Recall:          {rec:.4f}")
    print(f"F1-Score:        {f1:.4f}")
    
    print("\n=== SKLEARN EVALUATOR (Comparison) ===")
    print(f"Accuracy:        {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision:       {precision_score(y_test, y_pred, zero_division=0):.4f}")
    print(f"Recall:          {recall_score(y_test, y_pred, zero_division=0):.4f}")
    print(f"F1-Score:        {f1_score(y_test, y_pred, zero_division=0):.4f}")
